import { createHash } from 'node:crypto';
import { mkdir, readFile, writeFile } from 'node:fs/promises';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const toolDirectory = dirname( fileURLToPath( import.meta.url ) );
const pluginDirectory = resolve( toolDirectory, '..' );
const sourcePath = resolve( pluginDirectory, 'assets/src/index.js' );
const administrationSourcePath = resolve( pluginDirectory, 'assets/src/administration.js' );
const administrationAnalyticsSourcePath = resolve( pluginDirectory, 'assets/src/administration-analytics.js' );
const administrationToolsSourcePath = resolve( pluginDirectory, 'assets/src/administration-tools.js' );
const styleSourcePath = resolve( pluginDirectory, 'assets/src/index.css' );
const administrationStyleSourcePath = resolve( pluginDirectory, 'assets/src/administration.css' );
const administrationAnalyticsStyleSourcePath = resolve( pluginDirectory, 'assets/src/administration-analytics.css' );
const administrationToolsStyleSourcePath = resolve( pluginDirectory, 'assets/src/administration-tools.css' );
const storeCreditSourcePath = resolve( pluginDirectory, 'assets/src/store-credit.js' );
const storeCreditStyleSourcePath = resolve( pluginDirectory, 'assets/src/store-credit.css' );
const buildDirectory = resolve( pluginDirectory, 'assets/build' );
const outputPath = resolve( buildDirectory, 'index.js' );
const styleOutputPath = resolve( buildDirectory, 'index.css' );
const assetPath = resolve( buildDirectory, 'index.asset.php' );
const storeCreditOutputPath = resolve( buildDirectory, 'store-credit.js' );
const storeCreditStyleOutputPath = resolve( buildDirectory, 'store-credit.css' );
const storeCreditAssetPath = resolve( buildDirectory, 'store-credit.asset.php' );

const [ source, administrationSource, administrationAnalyticsSource, administrationToolsSource, styleSource, administrationStyleSource, administrationAnalyticsStyleSource, administrationToolsStyleSource, storeCreditSource, storeCreditStyleSource ] = await Promise.all( [
	readFile( sourcePath, 'utf8' ),
	readFile( administrationSourcePath, 'utf8' ),
	readFile( administrationAnalyticsSourcePath, 'utf8' ),
	readFile( administrationToolsSourcePath, 'utf8' ),
	readFile( styleSourcePath, 'utf8' ),
	readFile( administrationStyleSourcePath, 'utf8' ),
	readFile( administrationAnalyticsStyleSourcePath, 'utf8' ),
	readFile( administrationToolsStyleSourcePath, 'utf8' ),
	readFile( storeCreditSourcePath, 'utf8' ),
	readFile( storeCreditStyleSourcePath, 'utf8' ),
] );
const banner = '/** PromoGuard administration asset. Generated by npm run build. */\n';
const storeCreditBanner = '/** PromoGuard store-credit asset. Generated by npm run build. */\n';
const output = `${ banner }${ source }\n${ administrationSource }\n${ administrationAnalyticsSource }\n${ administrationToolsSource }`;
const styleOutput = `${ banner }${ styleSource }\n${ administrationStyleSource }\n${ administrationAnalyticsStyleSource }\n${ administrationToolsStyleSource }`;
const storeCreditOutput = `${ storeCreditBanner }${ storeCreditSource }`;
const storeCreditStyleOutput = `${ storeCreditBanner }${ storeCreditStyleSource }`;

function contentVersion( ...contents ) {
	const hash = createHash( 'sha256' );
	contents.forEach( ( content ) => hash.update( content ) );
	return hash.digest( 'hex' ).slice( 0, 12 );
}

function assetMetadata( dependencies, version ) {
	const dependencyList = dependencies.map( ( dependency ) => `'${ dependency }'` ).join( ', ' );
	return `<?php
return array(
\t'dependencies' => array( ${ dependencyList } ),
\t'version'     => '${ version }',
);
`;
}

// Content hashes provide deterministic cache invalidation without timestamps.
const version = contentVersion( output, styleOutput );
const storeCreditVersion = contentVersion( storeCreditOutput, storeCreditStyleOutput );

await mkdir( buildDirectory, { recursive: true } );
await Promise.all( [
	writeFile( outputPath, output, 'utf8' ),
	writeFile( styleOutputPath, styleOutput, 'utf8' ),
	writeFile( assetPath, assetMetadata( [ 'wp-i18n' ], version ), 'utf8' ),
	writeFile( storeCreditOutputPath, storeCreditOutput, 'utf8' ),
	writeFile( storeCreditStyleOutputPath, storeCreditStyleOutput, 'utf8' ),
	writeFile(
		storeCreditAssetPath,
		assetMetadata( [ 'wp-element', 'wp-i18n', 'wp-plugins', 'wc-blocks-checkout' ], storeCreditVersion ),
		'utf8'
	),
] );

console.log( `Built administration assets with version ${ version }.` );
console.log( `Built store-credit assets with version ${ storeCreditVersion }.` );
