import { createHash } from 'node:crypto';
import { mkdir, readFile, writeFile } from 'node:fs/promises';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const toolDirectory = dirname( fileURLToPath( import.meta.url ) );
const pluginDirectory = resolve( toolDirectory, '..' );
const sourcePath = resolve( pluginDirectory, 'assets/src/index.js' );
const administrationSourcePath = resolve( pluginDirectory, 'assets/src/administration.js' );
const administrationAnalyticsSourcePath = resolve( pluginDirectory, 'assets/src/administration-analytics.js' );
const administrationToolsSourcePath = resolve( pluginDirectory, 'assets/src/administration-tools.js' );
const styleSourcePath = resolve( pluginDirectory, 'assets/src/index.css' );
const administrationStyleSourcePath = resolve( pluginDirectory, 'assets/src/administration.css' );
const administrationAnalyticsStyleSourcePath = resolve( pluginDirectory, 'assets/src/administration-analytics.css' );
const administrationToolsStyleSourcePath = resolve( pluginDirectory, 'assets/src/administration-tools.css' );
const buildDirectory = resolve( pluginDirectory, 'assets/build' );
const outputPath = resolve( buildDirectory, 'index.js' );
const styleOutputPath = resolve( buildDirectory, 'index.css' );
const assetPath = resolve( buildDirectory, 'index.asset.php' );

const [ source, administrationSource, administrationAnalyticsSource, administrationToolsSource, styleSource, administrationStyleSource, administrationAnalyticsStyleSource, administrationToolsStyleSource ] = await Promise.all( [
	readFile( sourcePath, 'utf8' ),
	readFile( administrationSourcePath, 'utf8' ),
	readFile( administrationAnalyticsSourcePath, 'utf8' ),
	readFile( administrationToolsSourcePath, 'utf8' ),
	readFile( styleSourcePath, 'utf8' ),
	readFile( administrationStyleSourcePath, 'utf8' ),
	readFile( administrationAnalyticsStyleSourcePath, 'utf8' ),
	readFile( administrationToolsStyleSourcePath, 'utf8' ),
] );
const banner = '/** PromoGuard administration asset. Generated by npm run build. */\n';
const output = `${ banner }${ source }\n${ administrationSource }\n${ administrationAnalyticsSource }\n${ administrationToolsSource }`;
const styleOutput = `${ banner }${ styleSource }\n${ administrationStyleSource }\n${ administrationAnalyticsStyleSource }\n${ administrationToolsStyleSource }`;

// A content hash gives WordPress deterministic cache invalidation without a
// timestamp, so identical source produces identical build artifacts.
const version = createHash( 'sha256' )
	.update( output )
	.update( styleOutput )
	.digest( 'hex' )
	.slice( 0, 12 );
const assetMetadata = `<?php
return array(
\t'dependencies' => array( 'wp-i18n' ),
\t'version'     => '${ version }',
);
`;

await mkdir( buildDirectory, { recursive: true } );
await Promise.all( [
	writeFile( outputPath, output, 'utf8' ),
	writeFile( styleOutputPath, styleOutput, 'utf8' ),
	writeFile( assetPath, assetMetadata, 'utf8' ),
] );

console.log( `Built assets with version ${ version }.` );
